services:
  postgres:
    build:
      context: .
      dockerfile: docker/postgres-sqlite/Dockerfile
    container_name: anti-cheat-postgres
    environment:
      POSTGRES_DB: coreprotect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./data/raw/CoreProtect:/sqlite
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: